#!/usr/bin/env bash
# Idempotent Debian 13 installer for the Quadlets in this bundle.
set -Eeuo pipefail
umask 077

readonly PREFIX=/etc/crypto-daemons
readonly QUADLET_DIR=/etc/containers/systemd
readonly DATA_DIR=/srv/crypto-daemons
readonly ARTI_IMAGE=localhost/crypto-arti:2.5.1
# Every daemon image is built locally from the upstream project's own signed
# release tarball; the pinned checksums live in containers/*.Containerfile.
readonly BITCOIN_VERSION=31.1
readonly LITECOIN_VERSION=0.21.5.6
readonly MONERO_VERSION=0.18.5.1
readonly BITCOIN_IMAGE="localhost/crypto-bitcoin:${BITCOIN_VERSION}"
readonly LITECOIN_IMAGE="localhost/crypto-litecoin:${LITECOIN_VERSION}"
readonly MONERO_IMAGE="localhost/crypto-monero:${MONERO_VERSION}"
readonly BUNDLE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

require_root() {
  if [[ ${EUID} -ne 0 ]]; then
    echo 'Run as root (for example: sudo ./setup.sh).' >&2
    exit 1
  fi
}

require_digest() {
  local name=$1 value=$2
  if [[ -z ${value} || ${value} != *@sha256:* ]]; then
    printf '%s must be an immutable image reference ending in @sha256:…\n' "$name" >&2
    exit 2
  fi
}

maybe_install_podman_desktop() {
  # Desktop is optional and deliberately defaults to no: servers are commonly
  # headless, while Flatpak is per-user rather than a system daemon dependency.
  local answer=${INSTALL_PODMAN_DESKTOP:-}
  local desktop_user=${PODMAN_DESKTOP_USER:-${SUDO_USER:-}}
  local desktop_home
  if [[ -z $answer && -t 0 ]]; then
    read -r -p 'Install Podman Desktop for a local GUI? [y/N] ' answer
  fi
  case ${answer,,} in
    y|yes)
      if [[ -z $desktop_user || $desktop_user == root ]]; then
        echo 'Set PODMAN_DESKTOP_USER to the desktop login when installing as root.' >&2
        return 1
      fi
      desktop_home=$(getent passwd "$desktop_user" | cut -d: -f6)
      if [[ -z $desktop_home ]]; then
        echo "Podman Desktop user does not exist: $desktop_user" >&2
        return 1
      fi
      apt-get install -y --no-install-recommends flatpak
      runuser -u "$desktop_user" -- env HOME="$desktop_home" \
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
      runuser -u "$desktop_user" -- env HOME="$desktop_home" \
        flatpak install -y --user flathub io.podman_desktop.PodmanDesktop
      echo "Podman Desktop installed for $desktop_user."
      ;;
    ''|n|no) ;;
    *)
      echo "Unrecognised INSTALL_PODMAN_DESKTOP value: $answer (use yes or no)." >&2
      return 2
      ;;
  esac
}

random_password() { openssl rand -hex 32; }

rpcauth_line() {
  local user=$1 password=$2 salt hash
  salt=$(openssl rand -hex 16)
  hash=$(printf '%s' "$password" | openssl dgst -sha256 -hmac "$salt" -binary | xxd -p -c 256)
  printf 'rpcauth=%s:%s$%s\n' "$user" "$salt" "$hash"
}

ensure_credential() {
  local name=$1
  local credential_file="$PREFIX/secrets/rpc-credentials.env"
  if ! grep -q "^${name}=" "$credential_file"; then
    printf '%s=%s\n' "$name" "$(random_password)" >>"$credential_file"
  fi
}

load_credentials() {
  # This file is created locally with 0600 permissions and contains only values
  # generated by this script. shellcheck disable=SC1090
  set -a
  . "$PREFIX/secrets/rpc-credentials.env"
  set +a
}

initialize_secrets() {
  local credential_file="$PREFIX/secrets/rpc-credentials.env"
  install -d -m 0700 "$PREFIX/secrets"
  touch "$credential_file"
  chmod 0600 "$credential_file"
  touch "$PREFIX/secrets/default-wallet-addresses.env"
  chmod 0600 "$PREFIX/secrets/default-wallet-addresses.env"
  ensure_credential BITCOIN_RPC_PASSWORD
  ensure_credential LITECOIN_RPC_PASSWORD
  ensure_credential MONERO_RPC_PASSWORD
  ensure_credential BITCOIN_WALLET_PASSPHRASE
  ensure_credential LITECOIN_WALLET_PASSPHRASE
  ensure_credential MONERO_WALLET_PASSWORD
  ensure_credential MONERO_WALLET_RPC_PASSWORD
  if ! grep -q '^BITCOIN_RPC_USER=' "$credential_file"; then printf 'BITCOIN_RPC_USER=bitcoinrpc\n' >>"$credential_file"; fi
  if ! grep -q '^LITECOIN_RPC_USER=' "$credential_file"; then printf 'LITECOIN_RPC_USER=litecoinrpc\n' >>"$credential_file"; fi
  if ! grep -q '^MONERO_RPC_USER=' "$credential_file"; then printf 'MONERO_RPC_USER=monerorpc\n' >>"$credential_file"; fi
  if ! grep -q '^MONERO_WALLET_RPC_USER=' "$credential_file"; then printf 'MONERO_WALLET_RPC_USER=monerowalletrpc\n' >>"$credential_file"; fi
  load_credentials

  [[ -f $PREFIX/secrets/bitcoin-rpcauth.conf ]] || rpcauth_line "$BITCOIN_RPC_USER" "$BITCOIN_RPC_PASSWORD" >"$PREFIX/secrets/bitcoin-rpcauth.conf"
  [[ -f $PREFIX/secrets/litecoin-rpcauth.conf ]] || rpcauth_line "$LITECOIN_RPC_USER" "$LITECOIN_RPC_PASSWORD" >"$PREFIX/secrets/litecoin-rpcauth.conf"
  [[ -f $PREFIX/secrets/monero-rpc.conf ]] || printf 'rpc-login=%s:%s\n' "$MONERO_RPC_USER" "$MONERO_RPC_PASSWORD" >"$PREFIX/secrets/monero-rpc.conf"
  printf '%s\n' "$MONERO_WALLET_PASSWORD" >"$PREFIX/secrets/monero-wallet-password"
  printf 'rpc-login=%s:%s\ndaemon-login=%s:%s\n' \
    "$MONERO_WALLET_RPC_USER" "$MONERO_WALLET_RPC_PASSWORD" \
    "$MONERO_RPC_USER" "$MONERO_RPC_PASSWORD" >"$PREFIX/secrets/monero-wallet-rpc.conf"
  chmod 0600 "$PREFIX/secrets"/*

  echo "Credentials and wallet passphrases are in $credential_file (mode 0600)."
  echo 'Copy them to an offline password manager before funding any wallet.'
}

wait_for_core_rpc() {
  local container=$1 cli=$2 attempt
  for attempt in {1..120}; do
    if podman exec "$container" "$cli" -datadir=/data getblockchaininfo >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "$container RPC did not become ready within four minutes." >&2
  return 1
}

ensure_core_wallet() {
  # Litecoin Core is Bitcoin Core 0.21-based and rejects descriptor wallets
  # outright, so the wallet type is per-chain rather than assumed.
  local container=$1 cli=$2 passphrase_var=$3 address_var=$4 descriptors=$5 wallet_list address
  wait_for_core_rpc "$container" "$cli"
  wallet_list=$(podman exec "$container" "$cli" -datadir=/data listwalletdir)
  if ! grep -Eq '"name"[[:space:]]*:[[:space:]]*"default"' <<<"$wallet_list"; then
    podman exec "$container" "$cli" -datadir=/data -named createwallet \
      wallet_name=default disable_private_keys=false blank=false \
      "passphrase=${!passphrase_var}" avoid_reuse=true "descriptors=${descriptors}" >/dev/null
  fi
  podman exec "$container" "$cli" -datadir=/data -rpcwallet=default getwalletinfo >/dev/null
  if ! grep -q "^${address_var}=" "$PREFIX/secrets/default-wallet-addresses.env"; then
    address=$(podman exec "$container" "$cli" -datadir=/data -rpcwallet=default getnewaddress default bech32)
    # Never record an empty address: it would mask a failed wallet setup and be
    # copied out as a receive address.
    if [[ -z $address ]]; then
      echo "$container did not return a receive address; wallet setup incomplete." >&2
      return 1
    fi
    printf '%s=%s\n' "$address_var" "$address" >>"$PREFIX/secrets/default-wallet-addresses.env"
  fi
}

ensure_monero_wallet() {
  local recovery_file="$PREFIX/secrets/monero-default-wallet-recovery.txt"
  if [[ ! -s $DATA_DIR/monero-wallet/default.keys ]]; then
    # Keep all CLI output (including the mnemonic) out of the terminal/journal.
    # The temporary CLI runs offline: it only creates the encrypted wallet.
    # The trailing `seed` command re-prompts for the password on stdin even when
    # --password-file created the wallet; without it the wallet is still created
    # but the recovery file records "Error: invalid password" instead of the
    # mnemonic, leaving a funded wallet with no seed backup.
    printf '%s\n' "$MONERO_WALLET_PASSWORD" | podman run --rm -i --network none --user 0 \
      --entrypoint monero-wallet-cli \
      -v "$DATA_DIR/monero-wallet:/wallets" \
      -v "$PREFIX/secrets:/secrets:ro" \
      "$MONERO_IMAGE" --generate-new-wallet /wallets/default \
      --password-file /secrets/monero-wallet-password \
      --mnemonic-language English --offline --create-address-file seed >"$recovery_file"
    chmod 0600 "$recovery_file"
    [[ -s $DATA_DIR/monero-wallet/default.keys ]] || {
      echo 'Monero wallet creation failed; inspect the protected recovery output.' >&2
      return 1
    }
    if grep -q 'Error:' "$recovery_file"; then
      echo 'Monero mnemonic was not captured; refusing to leave a wallet with no seed backup.' >&2
      echo "Remove $DATA_DIR/monero-wallet/default* and rerun after investigating." >&2
      return 1
    fi
  fi
  if ! grep -q '^MONERO_DEFAULT_ADDRESS=' "$PREFIX/secrets/default-wallet-addresses.env"; then
    printf 'MONERO_DEFAULT_ADDRESS=%s\n' "$(tr -d '\r\n' <"$DATA_DIR/monero-wallet/default.address.txt")" >>"$PREFIX/secrets/default-wallet-addresses.env"
  fi
}

autoload_wallet() {
  # Only add -wallet once the wallet exists; naming a missing wallet is a
  # startup error, and the daemon has to come up before it can be created.
  local name=$1 conf=$2
  if [[ -e $DATA_DIR/$name/wallets/default ]] && ! grep -qx 'wallet=default' "$conf"; then
    printf 'wallet=default\n' >>"$conf"
  fi
}

build_daemon_image() {
  # The Containerfile downloads the upstream release and checks it against a
  # checksum pinned in the file itself, so a tampered download fails the build.
  local chain=$1 tag=$2
  install -m 0644 "$BUNDLE_DIR/containers/$chain.Containerfile" "$PREFIX/$chain.Containerfile"
  podman build --pull=always --tag "$tag" \
    --build-arg "FETCH_IMAGE=$BASE_IMAGE" \
    --build-arg "RUNTIME_IMAGE=$BASE_IMAGE" \
    --file "$PREFIX/$chain.Containerfile" "$PREFIX"
}

install_template() {
  local input=$1 output=$2
  sed \
    -e "s|@@BITCOIN_IMAGE@@|${BITCOIN_IMAGE}|g" \
    -e "s|@@LITECOIN_IMAGE@@|${LITECOIN_IMAGE}|g" \
    -e "s|@@MONERO_IMAGE@@|${MONERO_IMAGE}|g" \
    "$input" >"$output"
}

main() {
  require_root
  # Only the two build base images come from a registry now, and both must still
  # be immutable: they are the root of trust for every binary built below.
  require_digest BASE_IMAGE "${BASE_IMAGE:-}"
  require_digest ARTI_RUST_IMAGE "${ARTI_RUST_IMAGE:-}"

  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends podman uidmap slirp4netns fuse-overlayfs \
    ca-certificates openssl xxd
  maybe_install_podman_desktop

  install -d -m 0755 "$PREFIX" "$QUADLET_DIR" "$DATA_DIR" \
    "$DATA_DIR/arti" "$DATA_DIR/bitcoin" "$DATA_DIR/litecoin" "$DATA_DIR/monero"
  # -walletdir must already exist or the daemon refuses to start.
  install -d -m 0700 "$DATA_DIR/bitcoin/wallets" "$DATA_DIR/litecoin/wallets"
  install -d -m 0700 "$DATA_DIR/monero-wallet"
  initialize_secrets

  install -m 0644 "$BUNDLE_DIR/config/arti.toml" "$PREFIX/arti.toml"
  install -m 0644 "$BUNDLE_DIR/config/bitcoin.conf" "$PREFIX/bitcoin.conf"
  install -m 0644 "$BUNDLE_DIR/config/litecoin.conf" "$PREFIX/litecoin.conf"
  autoload_wallet bitcoin "$PREFIX/bitcoin.conf"
  autoload_wallet litecoin "$PREFIX/litecoin.conf"
  # monerod has no includeconf equivalent; build its config without printing its secret.
  install -m 0600 "$BUNDLE_DIR/config/monero.conf" "$PREFIX/monero.conf"
  sed -n '1,$p' "$PREFIX/secrets/monero-rpc.conf" >>"$PREFIX/monero.conf"
  install -m 0600 "$BUNDLE_DIR/config/monero-wallet-rpc.conf" "$PREFIX/monero-wallet-rpc.conf"
  sed -n '1,$p' "$PREFIX/secrets/monero-wallet-rpc.conf" >>"$PREFIX/monero-wallet-rpc.conf"

  install -m 0600 "$PREFIX/secrets/bitcoin-rpcauth.conf" "$PREFIX/bitcoin-rpcauth.conf"
  install -m 0600 "$PREFIX/secrets/litecoin-rpcauth.conf" "$PREFIX/litecoin-rpcauth.conf"
  {
    printf 'BITCOIN_IMAGE=%s\n' "$BITCOIN_IMAGE"
    printf 'LITECOIN_IMAGE=%s\n' "$LITECOIN_IMAGE"
    printf 'MONERO_IMAGE=%s\n' "$MONERO_IMAGE"
    printf 'ARTI_IMAGE=%s\n' "$ARTI_IMAGE"
    printf 'BASE_IMAGE=%s\n' "$BASE_IMAGE"
    printf 'ARTI_RUST_IMAGE=%s\n' "$ARTI_RUST_IMAGE"
  } >"$PREFIX/images.env"

  install -m 0644 "$BUNDLE_DIR/containers/arti.Containerfile" "$PREFIX/arti.Containerfile"
  podman build --pull=always --tag "$ARTI_IMAGE" \
    --build-arg "RUST_IMAGE=$ARTI_RUST_IMAGE" \
    --build-arg "RUNTIME_IMAGE=$BASE_IMAGE" \
    --file "$PREFIX/arti.Containerfile" "$PREFIX"
  build_daemon_image bitcoin "$BITCOIN_IMAGE"
  build_daemon_image litecoin "$LITECOIN_IMAGE"
  build_daemon_image monero "$MONERO_IMAGE"

  install -m 0644 "$BUNDLE_DIR/quadlet/crypto.network" "$QUADLET_DIR/crypto.network"
  install -m 0644 "$BUNDLE_DIR/quadlet/arti.container" "$QUADLET_DIR/arti.container"
  install_template "$BUNDLE_DIR/quadlet/bitcoin.container" "$QUADLET_DIR/bitcoin.container"
  install_template "$BUNDLE_DIR/quadlet/litecoin.container" "$QUADLET_DIR/litecoin.container"
  install_template "$BUNDLE_DIR/quadlet/monero.container" "$QUADLET_DIR/monero.container"
  install_template "$BUNDLE_DIR/quadlet/monero-wallet-rpc.container" "$QUADLET_DIR/monero-wallet-rpc.container"

  systemctl daemon-reload
  # Quadlet-generated units cannot be enabled; the generator applies each unit's
  # [Install] section itself, so starting them is all that is required.
  systemctl start arti.service bitcoin.service litecoin.service monero.service
  ensure_core_wallet bitcoin bitcoin-cli BITCOIN_WALLET_PASSPHRASE BITCOIN_DEFAULT_ADDRESS true
  ensure_core_wallet litecoin litecoin-cli LITECOIN_WALLET_PASSPHRASE LITECOIN_DEFAULT_ADDRESS false
  ensure_monero_wallet
  systemctl start monero-wallet-rpc.service
  echo 'Installation complete.  Services may take time to bootstrap/sync.'
  echo "Receive addresses: $PREFIX/secrets/default-wallet-addresses.env"
  echo "Monero recovery output: $PREFIX/secrets/monero-default-wallet-recovery.txt"
}

main "$@"
